import categories_spans_cospans_relations_partial_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace categories_spans_cospans_relations_partial_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end categories_spans_cospans_relations_partial_theorem_canonical_lane_mathlib
end HautevilleHouse
